robheyes/lifxcode

src/main/groovy/ShortFrame.groovy, src/test/groovy/ShortFrameTest.groovy
=> Changed the internals of Buffer

LIFXMasterApp.groovy, src/main/groovy/Parser.groovy, src/test/groovy/ParserTest.groovy
=> A bit of cleanup

src/main/groovy/Parser.groovy
Use unsigned bitwise manipulation rather than multiplication
=> Use dot notation for the maps.

LIFXMasterApp.groovy, src/main/groovy/Parser.groovy, src/test/groovy/ParserTest.groovy
=> Better typing of the data

LIFXColor.groovy, LIFXDiscovery.groovy
Rename LIFXMasterApp as LIFXDiscovery
Resolve some type issues
=> Now cache the descriptors

LIFXColor.groovy, LIFXDiscovery.groovy
=> Add removeChildDevices

LIFXColor.groovy, LIFXMasterApp.groovy
Much of the heavy lifting, ie utility methods are now in LIFXMasterApp
Now fires off 4 UDP broadcasts for each ip address, will have to see
whether these get received successfully.
=> As yet untested

LIFXColor.groovy, LIFXDiscovery.groovy, LIFXMasterApp.groovy
Delay between UDP broadcasts
Multiple scanning passes
=> A lot of clean up

LIFXDiscovery.groovy, LIFXMasterApp.groovy, README.md
Clean up
Rename LIFX+ Color device to LIFXPlus Color
Update README.md
=> Configurable maxScanPasses

LIFXColor.groovy, LIFXDiscovery.groovy, LIFXMasterApp.groovy
Don't scan any known IPs for devices on subsequent passes - should help when there are lots of devices
=> Add input to app to configure #scans, command pause time, etc

LIFXColor.groovy, LIFXDiscovery.groovy, LIFXMasterApp.groovy
App UI now reports on the progress of the scan every 10 seconds
=> Added support for setColorTemperature

LIFXDiscovery.groovy, LIFXMasterApp.groovy
No longer uses pauseExecution, now uses a queue and runInMillis
Some code cleanup
=> Discovery now shows a progress percentage.

LIFXColor.groovy, LIFXDayAndDusk.groovy, LIFXDiscovery.groovy, LIFXMasterApp.groovy, LIFXMultiZone.groovy, LIFXPlusColor.groovy, LIFXTile.groovy, LIFXWhite.groovy, LIFXWhiteMono.groovy
* Improved rgbToHsv (no longer allows -ve values)
* Added advice about using groups
* Updated styling to remove some unintended consequences
* Added device name prefix to preferences
* Suppressed warnings, and marked more methods private
* Duration scaling now only done in a couple of places
* colorName attribute is cleared when the colour is unknown
* Removed descriptor caching, it's really not needed and had a bit of overhead.
* Better grouping of methods according to public/private
* Added lazy field fullColourMap so it's only evaluated once for all colours
=> Removed dead code

LIFXMasterApp.groovy
. Not requiring acknowledgments
. Not updating the device's name and label when setting state
=> Reduce popcorning by

LIFXDayAndDusk.groovy, LIFXMultiZone.groovy, LIFXPlusColor.groovy, LIFXTile.groovy, LIFXWhite.groovy, LIFXWhiteMono.groovy
Change multizone driver to warn on attempt to set level
=> Add missing getUseActivityLog() to drivers that were missing it.

LIFXColor.groovy, LIFXDayAndDusk.groovy, LIFXMasterApp.groovy, LIFXMultiZone.groovy, LIFXPlusColor.groovy, LIFXTile.groovy, LIFXWhite.groovy, LIFXWhiteMono.groovy, README.md
=> Updated the readme

LIFXMultiZone.groovy, README.md
* Remove out-of-date limitations
* fix typo in `setColorTemperature` which prevented proper functionality
=> README updates + MZ setColorTemp fix

LIFXMasterApp.groovy, LIFXMultiZone.groovy, README.md
* includes PR #83
* Add device IDs 62 and 63
=> Device types

LIFXColor.groovy, LIFXDayAndDusk.groovy, LIFXMasterApp.groovy, LIFXMultiZone.groovy, LIFXPlusColor.groovy, LIFXWhite.groovy
add setWaveform command
includes pr #85
=> Waveform v2

LIFXMasterApp.groovy
* Add new devices types:
* 64: LIFX+ A19
* 65: LIFX+ BR30
* 81: LIFX Candle Warm to White
* 82: LIFX Filament
=> add new device types (excluding candle color)

LIFXDayAndDusk.groovy, LIFXWhiteMono.groovy, README.md
Add SetWaveform to LIFXWhiteMono
Update README to refer to HPM
=> Add ChangeLevel to LIFXDayAndDusk

LIFXColor.groovy, LIFXDayAndDusk.groovy, LIFXMasterApp.groovy, LIFXMultiZone.groovy, LIFXMultiZoneChild.groovy, LIFXPlusColor.groovy, LIFXWhite.groovy, LIFXWhiteMono.groovy, packageManifest.json
Add new devices
Bump minor version
=> Clean up some of the capabilities

LIFXColor.groovy, LIFXDayAndDusk.groovy, LIFXMasterApp.groovy, LIFXPlusColor.groovy, LIFXTile.groovy, LIFXWhite.groovy, packageManifest.json
This is for Hubitat Elevation v 2.2.8
=> Change to setColorTemperature in all drivers
